### ISSUE TITLE
discord机器人始终无法回复消息

### ISSUE THREAD

**Issue by dalamudx** [nonebot/adapter-discord#33]
cc [discord机器人始终无法回复消息](https://github.com/orgs/nonebot/discussions/468)
尝试装了master版本虽然日志里看到能捕获，但是数据验证报错
![image](https://github.com/nonebot/adapter-discord/assets/88395653/50824e3f-1a8f-4080-a4c2-c57ab2c0ef18)
![image](https://github.com/nonebot/adapter-discord/assets/88395653/ec209451-8fe0-4c57-bc12-65b96321d5e2)

**Comment by Autuamn** [comment]
麻烦帮忙试试最新 master 版本

可以把日志等级开到 `TRACE` 吗，我复现不出你这个问题

**Comment by shoucandanghehe** [comment]
> 我复现不出你这个问题

这个问题是 `Pydantic V2` 行为改变导致的，应该会被我的pr修复（

**Comment by dalamudx** [comment]
对，上次合入的[PR](https://github.com/nonebot/adapter-discord/pull/34)已经修复这个问题了，我关一下
