### ISSUE TITLE
是否必须at机器人才能响应指令

### ISSUE THREAD

**Issue by SonderXiaoming** [nonebot/adapter-discord#8]
用的示例代码，我看规则是空的，应该来说是没有这个要求（nb2新人）

**Comment by CMHopeSunshine** [comment]
默认不需要，可配置响应器的rule中配置to_me规则来要求艾特触发。

**Comment by SonderXiaoming** [comment]
![image](https://github.com/nonebot/adapter-discord/assets/98363578/f7897259-e1f2-40e2-9231-d88155fd5de4)
但是我cv的示例代码，不在channel中at就不响应

**Comment by CMHopeSunshine** [comment]
不艾特的话能接收到事件不，不能的话可能是intent设置问题

**Comment by SonderXiaoming** [comment]
是我没开intent，没事了
